#Step 2 of the project has been performed to perform the Sequence Quality Analysis
#This includes reading the sequence using BioPython, calculation of length, GC content for DNA
#In addition, I have also included the AT/GC ratio, presence of any ambiguous bases (N), complement sequence, reverse complement, transcription and translation sequence
print("Step 2: performed by Siddhesh Uday Sapre")
print("-"*90)
from Bio import SeqIO 
record = SeqIO.read("Otsutsugamushi_Karp_tsa47.fasta", "fasta")
Adenine_count_A = record.seq.count("A")
Thymine_count_T = record.seq.count("T")
Guanine_count_G = record.seq.count("G")
Cytosine_count_C = record.seq.count("C")
Ambiguous_count_N = record.seq.count("N")
AT_sum = (Adenine_count_A + Thymine_count_T)
GC_sum = (Guanine_count_G + Cytosine_count_C)
GC_content = (GC_sum * 100)
AT_GC_ratio = (AT_sum/GC_sum)
print("The complement sequence for query sequence is:", record.seq.complement())
print("-"*90)
print("The reverse complement sequence for query sequence is:",record.seq.reverse_complement())
print("-"*90)
print("The mRNA transcript for query sequence is:",record.seq.transcribe())
print("-"*90)
print("The translated amino acid sequence for query sequence is:",record.seq.translate())
print("-"*90)
print("The length of translated DNA sequence or amino acids is:", len(record.seq.translate()))
print("-"*90)
print("A content in this sequence is:", Adenine_count_A, "bp")
print("T content in this sequence is:", Thymine_count_T, "bp")
print("G content in this sequence is:", Guanine_count_G, "bp")
print("C content in this sequence is:", Cytosine_count_C, "bp")
print("Ambiguous or undetermined nucleotide content in this sequence is:",Ambiguous_count_N, "bp")
print("-"*90)
print("AT/GC ratio for the query sequence is:", AT_GC_ratio)
print("End of Quality check. All parameters fulfilled. The query sequence passed the quality checks successfully.")

